# Generated by Django 4.1.9 on 2023-06-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=60)),
                ('level', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('middleName', models.CharField(max_length=60)),
                ('lastName1', models.CharField(max_length=60)),
                ('lastName2', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=60)),
                ('birthDate', models.DateField()),
                ('img', models.ImageField(upload_to='my_cv/img')),
            ],
        ),
    ]
