# Generated by Django 4.1.9 on 2023-06-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='img',
            field=models.ImageField(upload_to='my_cv/static/my_cv/img'),
        ),
    ]
