# Generated by Django 4.1.9 on 2023-06-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0002_alter_personal_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='address',
            field=models.CharField(default='tibas', max_length=600),
            preserve_default=False,
        ),
    ]
