# Generated by Django 4.1.9 on 2023-06-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100)),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
                ('position', models.CharField(max_length=100)),
                ('jobDescription', models.CharField(max_length=1000)),
            ],
        ),
    ]
