# Generated by Django 4.1.9 on 2023-06-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0009_alter_workxp_todate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(max_length=100)),
                ('yearsPractice', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
