# Generated by Django 4.1.9 on 2023-06-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0010_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skillName',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='skills',
            name='yearsPractice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
