# Generated by Django 4.1.9 on 2023-06-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0012_alter_skills_yearspractice'),
    ]

    operations = [
        migrations.CreateModel(
            name='skillDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(max_length=500)),
                ('yearsPractice', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
        ),
    ]
