# Generated by Django 4.1.9 on 2023-06-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0013_skilldetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='yearsPractice',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
