# Generated by Django 4.1.9 on 2023-07-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0016_othervalues_alter_education_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilldetails',
            name='img',
            field=models.ImageField(default='none', upload_to='my_cv/static/my_cv/img/skills'),
            preserve_default=False,
        ),
    ]
