# Generated by Django 4.1.9 on 2023-07-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0017_skilldetails_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='github',
            field=models.CharField(default='manuel', max_length=100),
            preserve_default=False,
        ),
    ]
