# Generated by Django 4.1.9 on 2023-07-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0018_personal_github'),
    ]

    operations = [
        migrations.CreateModel(
            name='cvTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
