# Generated by Django 4.1.9 on 2023-07-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0019_cvtitles'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='my_cv/static/my_cv/img/certs'),
        ),
    ]
