# Generated by Django 4.1.4 on 2023-05-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gptApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randq',
            name='answer',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='randq',
            name='question',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
