# Generated by Django 4.1.9 on 2023-06-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gptApp', '0003_alter_randq_answer_alter_randq_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalsQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=200, null=True)),
                ('answer', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
