# Generated by Django 4.1.9 on 2023-06-26 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gptApp', '0008_anatoq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnatoQ',
        ),
    ]
