# Generated by Django 4.1.9 on 2023-07-06 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gptApp', '0011_category_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
