# Generated by Django 4.1.9 on 2023-07-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gptApp', '0012_remove_question_category_delete_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryId', models.IntegerField()),
                ('categoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('categoryId', models.IntegerField()),
            ],
        ),
    ]
