# Generated by Django 4.1.9 on 2023-07-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gptApp', '0015_category_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
