# Generated by Django 4.1.9 on 2023-07-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gptApp', '0018_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('categoryId', models.IntegerField()),
                ('answer', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
