# Generated by Django 4.1.9 on 2023-07-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gptApp', '0021_auto_20230709_0838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
