# Generated by Django 4.1.9 on 2023-07-13 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gptApp', '0023_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnatoQ',
        ),
        migrations.DeleteModel(
            name='AnimalsQ',
        ),
        migrations.DeleteModel(
            name='EnvironmentQ',
        ),
        migrations.DeleteModel(
            name='HealthQ',
        ),
        migrations.DeleteModel(
            name='MathQ',
        ),
        migrations.DeleteModel(
            name='RandQ',
        ),
    ]
